# Generated by Django 5.1.1 on 2024-12-19 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meetings21app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accommodation_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AgendaPageSpeakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speakerphoto', models.ImageField(upload_to='Agenda/Speakers')),
                ('speakername', models.CharField(max_length=150)),
                ('speaker_description', models.CharField(max_length=100)),
                ('speaker_linked_in_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommitteePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committe_page_main_heading', models.CharField(blank=True, max_length=150, null=True)),
                ('committe_card_heading', models.CharField(blank=True, max_length=120, null=True)),
                ('committe_card_description', models.TextField()),
                ('committe_card_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Contactpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HomePageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_page_banner_image', models.ImageField(upload_to='HomePageBanner/Images')),
                ('home_page_banner_text', models.CharField(blank=True, max_length=200, null=True)),
                ('home_page_banner_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomePageSubscribeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='HomePageTicketsPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='No_of_Nights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('night', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PresentationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentation_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Register_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionsPage_Abstracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstracts_heading', models.CharField(max_length=150)),
                ('abstracts_description', models.TextField()),
                ('abstracts_text', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionsPage_topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic_of_Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Prof.', 'Prof.'), ('Dr.', 'Dr.'), ('Ms.', 'Ms.'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.')], max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('affiliation', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Meetings21app.accommodation')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Meetings21app.country')),
                ('no_of_nights', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Meetings21app.no_of_nights')),
                ('register_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Meetings21app.register_category')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionsPage_Abstract_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Prof.', 'Prof.'), ('Dr.', 'Dr.'), ('Ms.', 'Ms.'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.')], max_length=100)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('university', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp_number', models.CharField(max_length=10)),
                ('title_of_abstract', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='Submission/submitabstract/File')),
                ('agree', models.BooleanField(default=True)),
                ('presentation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Meetings21app.presentationtype')),
                ('topic_of_interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Meetings21app.topic_of_interest')),
            ],
        ),
    ]
